version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: torrentio-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: torrentio_user
      POSTGRES_PASSWORD: torrentio_password
      POSTGRES_DB: torrentio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U torrentio_user -d torrentio"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: torrentio-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Prowlarr for torrent searching
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: torrentio-prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - prowlarr_config:/config
    ports:
      - "9696:9696"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696/"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 60s

  # Torrentio Addon service
  torrentio-addon:
    build:
      context: ./
    container_name: torrentio-addon
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      prowlarr:
        condition: service_started
    environment:
      - DATABASE_URI=postgres://torrentio_user:torrentio_password@postgres:5432/torrentio
      - REDIS_URI=redis://redis:6379
      - PROWLARR_BASE_URL=http://prowlarr:9696
      - PROWLARR_API_KEY=${PROWLARR_API_KEY:-}
      - PROWLARR_SEARCH_LIMIT=100
      - PROWLARR_PARALLEL_REQUESTS=10
      - OMDB_API_KEY=${OMDB_API_KEY:-}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    ports:
      - "7000:7000"

volumes:
  postgres_data:
    name: torrentio-postgres-data
  redis_data:
    name: torrentio-redis-data
  prowlarr_config:
    name: torrentio-prowlarr-config 